

CREATE TABLE Galpon (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    capacity NUMBER,
    Lote VARCHAR2(5),
    State VARCHAR2(10) DEFAULT 'A',
    Fecha DATE DEFAULT SYSDATE,
    Type VARCHAR2(30),
    Ubigeo_Id NUMBER,
    CONSTRAINT PK_GALPONES PRIMARY KEY (ID)
);


INSERT INTO Galpon (capacity, Lote, Type, Ubigeo_Id)
VALUES (100, '123 A', 'Manual', 1);
INSERT INTO Galpon (capacity, Lote, Type, Ubigeo_Id)
VALUES (150, '456 B', 'Automatico', 2);
INSERT INTO Galpon (capacity, Lote, State, Type, Ubigeo_Id)
VALUES (200, '789 C', 'B', 'Manual', 3);
INSERT INTO Galpon (capacity, Lote, Type, Ubigeo_Id)
VALUES (300, '111 E', 'Manual', 5);

SELECT * FROM GALPON;



CREATE OR REPLACE FUNCTION obtener_capacidad_galpon(p_id NUMBER) RETURN NUMBER IS
    capacidad_galpon NUMBER;
BEGIN
    SELECT capacity INTO capacidad_galpon FROM Galpon WHERE Id = p_id;
    RETURN capacidad_galpon;
END;


SELECT obtener_capacidad_galpon(4) AS Capacidad_Galpon FROM dual;

----------------------------------------------------------------



CREATE OR REPLACE FUNCTION TipoGalpon(p_tipo_ingreso VARCHAR2) RETURN NUMBER IS
    cantidad_galpones NUMBER;
BEGIN
    IF p_tipo_ingreso = 'Manual' THEN
        SELECT COUNT(*) INTO cantidad_galpones FROM Galpon WHERE Type = 'Manual';
    ELSIF p_tipo_ingreso = 'Automatico' THEN
        SELECT COUNT(*) INTO cantidad_galpones FROM Galpon WHERE Type = 'Automatico';
    ELSE
        cantidad_galpones := 0;
    END IF;
    
    RETURN cantidad_galpones;
END;


SELECT TipoGalpon('Automatico') AS Galpon_Atutomatico,
TipoGalpon('Manual') AS Galpon_Manual
FROM dual;

----------------------------------------------------------------


CREATE OR REPLACE FUNCTION Consultar_Estado_Galpon_ID (
    p_id IN NUMBER
)
RETURN VARCHAR2
IS
    estado_galpon VARCHAR2(10);
BEGIN
    SELECT State INTO estado_galpon FROM Galpon WHERE Id = p_id;
    RETURN estado_galpon;
END;

SELECT Consultar_Estado_Galpon_ID(3) AS Estado_Galpon_ID
FROM DUAL;

----------------------------------------------------------------

CREATE OR REPLACE FUNCTION Tipo_Mas_Comun_Galpon RETURN VARCHAR2
IS
    tipo_mas_comun VARCHAR2(30);
BEGIN
    SELECT Type INTO tipo_mas_comun
    FROM (
        SELECT Type, COUNT(*) AS cantidad
        FROM Galpon
        GROUP BY Type
        ORDER BY COUNT(*) DESC
    )
    WHERE ROWNUM = 1;
    
    RETURN tipo_mas_comun;
END;

SELECT Tipo_Mas_Comun_Galpon() AS Tipo_Mas_Comun FROM DUAL;


----------------------------------------------------------------


CREATE OR REPLACE FUNCTION CapacidadMayor(p_capacidad_minima NUMBER) RETURN NUMBER IS
    cantidad_galpones NUMBER;
BEGIN
    SELECT COUNT(*) INTO cantidad_galpones FROM Galpon WHERE capacity > p_capacidad_minima;
    
    RETURN cantidad_galpones;
END;

SELECT CapacidadMayor(300) AS Cantidad_Galpones_Mayor FROM dual;
SELECT * FROM GALPON;

