CREATE TABLE Galpon (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    capacity NUMBER,
    Lote VARCHAR2(5),
    State VARCHAR2(10) DEFAULT 'A',
    Fecha DATE DEFAULT SYSDATE,
    Type VARCHAR2(30),
    Ubigeo_Id NUMBER,
    CONSTRAINT PK_GALPONES PRIMARY KEY (ID)
);


CREATE TABLE Person (
    ID  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Document_Type char(3),
    Document_Number varchar2(15),
    Names varchar2(20),
    Last_Names varchar2(20),
    Cellphone_Number char(9),
    Email varchar2(90),
    role VARCHAR2(10),
    Password varchar2(20),
    State varchar2(10)  DEFAULT 'A',
    CONSTRAINT PK_PERSON PRIMARY KEY (ID)
) ;

SET SERVEROUTPUT ON;


-- fUNCIONES

CREATE OR REPLACE FUNCTION Tipo_Mas_Comun_Galpon RETURN VARCHAR2
IS tipo_mas_comun VARCHAR2(30);
BEGIN
    SELECT Type INTO tipo_mas_comun
    FROM (
        SELECT Type, COUNT(*) AS cantidad
        FROM Galpon
        GROUP BY Type
        ORDER BY COUNT(*) DESC
    )
    WHERE ROWNUM = 1;
    
    RETURN tipo_mas_comun;
END;
SELECT Tipo_Mas_Comun_Galpon() AS Tipo_Mas_Comun FROM DUAL;


-- Mostrar Datos por Consola
-- Listar dato por ID
DECLARE
    v_person_id NUMBER := 1;
    v_document_type CHAR(3);
    v_document_number VARCHAR2(15);
    v_names VARCHAR2(20);
    v_last_names VARCHAR2(20);
    v_cellphone_number CHAR(9);
    v_email VARCHAR2(90);
    v_state VARCHAR2(10);
BEGIN
    SELECT Document_Type, Document_Number, Names, Last_Names, Cellphone_Number, Email, State
    INTO v_document_type, v_document_number, v_names, v_last_names, v_cellphone_number, v_email, v_state
    FROM Person
    WHERE ID = v_person_id;
    
    DBMS_OUTPUT.PUT_LINE('Document Type: ' || v_document_type);
    DBMS_OUTPUT.PUT_LINE('Document Number: ' || v_document_number);
    DBMS_OUTPUT.PUT_LINE('Names: ' || v_names);
    DBMS_OUTPUT.PUT_LINE('Last Names: ' || v_last_names);
    DBMS_OUTPUT.PUT_LINE('Cellphone Number: ' || v_cellphone_number);
    DBMS_OUTPUT.PUT_LINE('Email: ' || v_email);
    DBMS_OUTPUT.PUT_LINE('State: ' || v_state);
END;


-- Joins

CREATE VIEW Sheds_Report AS
SELECT
    s.ID,
    s.CAPACITY,
    s.LOTE,
    s.TYPE,
    TO_CHAR(s.FECHA, 'dd-MM-yyyy') AS FECHA,
    u.ZONE,
    s.STATE
FROM 
    SHEDS s
JOIN 
    UBIGEO u ON s.UBIGEO_ID = u.ID;
    
    
Select* from Assignments

CREATE VIEW Assignaments_Report AS
SELECT
    a.ID,
    p.last_names || names AS ENCARGADO,
    s.lote,
    u.zone,
    TO_CHAR(s.FECHA, 'dd-MM-yyyy') AS FECHA,    
    a.STATE
FROM 
    Assignments a
JOIN 
    SHEDS s ON a.sheds_id = s.ID
JOIN 
    PERSON p ON a.person_id = p.ID
JOIN 
    Ubigeo u ON s.ubigeo_id = u.ID;



CREATE VIEW Production_Report AS
SELECT
    a.ID,
    a.person_id,
    p.Names AS Person_Names,
    p.Last_Names AS Person_Last_Names, 
    d.java_pink,
    d.unidad_pink,
    d.java_bankrupt,
    d.unidad_bankrupt,
    d.java_broken,
    d.unidad_broken,
    d.STATE,
    TO_CHAR(d.date_production, 'dd-MM-yyyy') AS Date_Production, 
    d.total_production
FROM 
    DETAIL_PRODUCTION d
JOIN 
    Assignments a ON d.assignments_ID = a.ID
JOIN 
    Person p ON a.person_id = p.ID;

    
